---
abstract: 'Supports making bundles of modules recursively'
author:
  - 'Jens Rehsack <rehsack@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Module::Runtime: '0'
  Test::Directory: '0'
  Test::More: '0.90'
  Test::WriteVariants: '0.005'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ExtUtils-BundleMaker
no_index:
  directory:
    - t
    - inc
recommends:
  CHI: '0'
  HTTP::Tiny::Mech: '0'
  MetaCPAN::Client: '1.003000'
  WWW::Mechanize::Cached: '0'
requires:
  File::Basename: '0'
  File::Path: '0'
  File::Slurp: '0'
  File::Spec: '0'
  MetaCPAN::Client: '0'
  Module::CoreList: '2.99'
  Module::Runtime: '0'
  Moo: '0'
  MooX::ConfigFromFile: '0'
  MooX::Options: '4.000'
  Params::Util: '0'
  version: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=ExtUtils-BundleMaker
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rehsack/ExtUtils-BundleMaker.git
version: '0.006'
